spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.71.136:3306/mobile_dj?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  redis:
    database: 0
    host: 192.168.71.136
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 0
        max-idle: 10
        min-idle: 0
    timeout: 300

mybatis:
  config-location: classpath:mybatis-config.xml
#server:
#  port: 443
#  ssl:
#    key-store: classpath:duniqb.jks
#    key-store-password: 6VivSq6w
#    key-store-type: JKS
#    key-alias: alias

local:
  host: http://192.168.1.10:8080/
  # 验证码图片放置的本机文件夹
  verifyPath: D:\verify\
  image: D:\img\
  # 轮播图片存放的本机文件夹
  slidePath: D:\slide\

# 教务
jw:
  host: 202.199.128.21

# 后勤爬虫的各种配置
logistics:
  host: https://nanqu.56team.com

# 小程序配置
mini:
  appId: wxe1f564d00f76340a
  secret: ec547e58ed84fcbbee3a7e24a5823cc8
