spring:
  application:
    name: mobile-dj
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ubuntu:3306/mobile_dj2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zlb/zlb/zlb
  redis:
    database: 0
    host: ubuntu
    port: 6379
    password: zlb/zlb/zlb
    timeout: 3000
  rabbitmq:
    addresses: ubuntu
    port: 5672
    username: admin
    password: admin
    connection-timeout: 3000
  mail:
    host: smtp.qq.com
    port:
    username: duniqb@qq.com
    password: syexthrjrulghdib
  cloud:
    nacos:
      discovery:
        server-addr: ubuntu:8848
    alicloud:
      access-key: LTAI4G7tsooSDhu5GLcsLYDD
      secret-key: xsAyLv8pmVEg8e2s3RHl28HXVFvNbD
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: mobile-dj


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


logging:
  level:
    cn.duniqb.mobile: debug

local:
  host: http://192.168.1.200:8080/
  # 验证码图片放置的本机文件夹
  verifyPath: D:\verify\
  image: D:\img\

# 教务
jw:
  host: 202.199.128.21

# 后勤爬虫的各种配置
repair:
  host: https://nanqu.56team.com

# 小程序配置
mini:
  appId: wxe1f564d00f76340a
  secret: ec547e58ed84fcbbee3a7e24a5823cc8

# 统一的访问路径前缀
server:
  servlet:
    context-path: /api/v2
  port: 8080
jasypt:
  encryptor:
    password: duniqb
