spring:
  application:
    name: mobile-dj
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.71.136:3306/mobile_dj?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  # Redis 配置
  redis:
    database: 0
    host: 192.168.71.136
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 0
        max-idle: 10
        min-idle: 0
    timeout: 300

mybatis:
  config-location: classpath:mybatis-config.xml

# 教务爬虫的各种配置
jw:
  # 本机 url，以供回传验证码地址
  localhost: http://localhost:8080/
  login:
    # 登录教务的 url
    loginUrl: http://202.199.128.21/academic/common/security/login.jsp
    # 发起教务登录的 url
    loginPostUrl: http://202.199.128.21/academic/j_acegi_security_check
  # 获取验证码的 url
  verifyUrl: http://202.199.128.21/academic/getCaptcha.do
  # 获取个人信息的 url
  getInfoUrl: http://202.199.128.21/academic/showPersonalInfo.do
  # 获取成绩的 url
  getScoreParamUrl: http://202.199.128.21/academic/manager/score/studentOwnScore.do
  # 获取等级考试的 url
  getGradeExam: http://202.199.128.21/academic/student/skilltest/skilltest.jsdo
  # 设置 Cookie 的参数
  cookie:
    domain: 202.199.128.21
    path: /academic
  # 验证码存放的本机文件夹
  verifyPath: D:\verify\

# 图书馆爬虫的各种配置
lib:
  # 发起馆藏查询的 url
  searchUrl: http://wxlib.djtu.edu.cn/wx/search.aspx
  # 显示图书详情的 url
  showBookUrl: http://wxlib.djtu.edu.cn/wx/ShowBook.aspx
  # 设置 Cookie 的参数
  cookie:
    domain: wxlib.djtu.edu.cn
    path: /

# 小程序配置
mini:
  appId: wxe1f564d00f76340a
  secret: ec547e58ed84fcbbee3a7e24a5823cc8
